.TH BUILD-CLASSPATH "1" "March 2006" "build-classpath (jpackage-utils) 1.7.0" "User Commands"
.SH NAME
build-classpath \- build a Java CLASSPATH with the named JARs
.SH SYNOPSIS
.B build-classpath
\fIJAR1\fR [\fIJAR2\fR... \fIJARn\fR]
.SH DESCRIPTION
Small utility to build a Java CLASSPATH with the named JARs.  The CLASSPATH
is returned to standard output.
.TP
.SH EXAMPLES
.TP
build-classpath tyrex saxon wsdl4j
will return a string to standard out that is a valid CLASSPATH containing
tyrex, saxon, and wsdl4j JARs.
.SH AUTHOR
Written by David Walluck
.SH REPORTING BUGS
Report bugs using JPackage Bugzilla (http://www.jpackage.org/bugzilla/)
