.TH DIFF-JARS "1" "March 2006" "diff-jars (jpackage-utils) 1.7.0" "User Commands"
.SH NAME
diff-jars \- output the differences between two JAR files
.SH SYNOPSIS
.B diff-jars
\fIJAR1\fR \fIJAR2\fR
.SH DESCRIPTION
Output the differences between two JAR files.
.SH AUTHOR
Written by Guillaume Rousse
.SH REPORTING BUGS
Report bugs using JPackage Bugzilla (http://www.jpackage.org/bugzilla/)
