#!/bin/sh -e
# Copyright (c) 2013 Red Hat, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the
#    distribution.
# 3. Neither the name of Red Hat nor the names of its
#    contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Authors: Mikolaj Izdebski <mizdebsk@redhat.com>

# A marker informing Tycho that mvn-rpmbuild was ran.
export TYCHO_MVN_RPMBUILD=true
unset TYCHO_MVN_LOCAL
export TYCHO_MVN_LOCAL

# Support local depmaps
depmap=/some/nonexistent/path
for arg in "$@"; do
    if egrep -q '^-Dmaven\.local\.depmap\.file=' <<<"$arg"; then
	depmap="$XMVN_RESOLV_DEPMAPS,"$(sed 's/[^=]*=//' <<<"$arg")
    fi
done

mkdir -p .xmvn/config.d
cat >>.xmvn/config.d/mvn-rpmbuild-config.xml <<EOF
<configuration>
  <resolverSettings>
    <!-- XMvn default repo location is .xm2, but for backwards-compatibility
         we use .m2 if called as mvn-rpmbuild. -->
    <localRepositories>
      <repository>.m2</repository>
    <localRepositories>
    <metadataRepositories>
      <repository>$depmap</repository>
    </metadataRepositories>
  </resolverSettings>
</configuration>
EOF

# Allow -Dmaven.local.effective.pom=false to be used to disable
# resolution from effective POM repository.
XMVN_COMPAT=19-rpmbuild
for arg in "$@"; do
    if egrep -q '^-Dmaven\.local\.effective\.pom=false' <<<"$arg"; then
	XMVN_COMPAT=19-rpmbuild-raw
    fi
done
export XMVN_COMPAT

# Install maven metadata for plugins in groups org.apache.maven.plugins
# and org.codehaus.mojo. This is to allow plugins in these groups to be
# used without giving groupId prefix.
for groupId in org/apache/maven/plugins org/codehaus/mojo; do
    mkdir -p "${XMVN_REPO_LOCAL}"/${groupId}
    ln -sf /etc/maven/metadata-${groupId////-}.xml \
        "${XMVN_REPO_LOCAL}"/${groupId}/maven-metadata-central.xml
done

# Maven needs to have M2_HOME exported. See: rhbz#912333
export M2_HOME=/usr/share/maven

# Extra arguments passed to JVM
export ADDITIONAL_OPTIONS="${ADDITIONAL_OPTIONS} ${MAVEN_OPTS}"

exec xmvn \
    --offline \
    --batch-mode \
    -Dmaven.repo.local="${XMVN_REPO_LOCAL}" \
    -Dmaven.home=${M2_HOME} \
    "${@}"
